name: Check docs
on:
  push:
    branches:
      - main

  pull_request:
      types: [opened, reopened, synchronize]
      paths:
          - "charts/**"
          - ".github/workflows/**"

jobs:
  test:
    name: Check for updated Helm Chart docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Check if README is missing updates
        run: |
          go install github.com/norwoodj/helm-docs/cmd/helm-docs@latest
          helm-docs
          git diff --exit-code charts/athens-proxy/README.md
